# Visualizar riesgo{#Visualizar_riesgo}

## Riskr

FROM: https://cran.r-project.org/web/packages/riskyr/vignettes/E_riskyr_primer.html


```{r riskyr-1, message=FALSE, warning=FALSE, fig.height=10, fig.width=8}
if (!require('riskyr')) install.packages('riskyr'); library('riskyr')

# Create a customized scenario: 
my.scenario <- riskyr(scen_lbl = "Identifying reoffenders", 
                      popu_lbl = "prison inmates", 
                      cond_lbl = "reoffending",
                      cond_true_lbl = "offends again", cond_false_lbl = "does not offend again",
                      dec_lbl = "test result",
                      dec_pos_lbl = "predict to\nreoffend", dec_neg_lbl = "predict to\nnot reoffend",
                      hi_lbl = "reoffender found", mi_lbl = "reoffender missed",
                      fa_lbl = "false accusation", cr_lbl = "correct release",
                      prev = .45,  # prevalence of being a reoffender. 
                      sens = .98,  # p( will reoffend | offends again )
                      spec = .46,  # p( will not reoffend | does not offend again )
                      fart =  NA,  # p( will reoffend | does not offend gain )
                      N = 753,     # population size
                      scen_src = "(a ficticious example)")


my.scenario <- scenarios$n6

summary(my.scenario)


plot(my.scenario, plot.type = "icons")

plot(my.scenario, plot.type = "tree", by = "dc")  # plot tree diagram (splitting N by decision)

plot(my.scenario, plot.type = "curve")  # plot default curve [what = c("prev", "PPV", "NPV")]:



```


```{r riskyr-2, message=FALSE, warning=FALSE, fig.height=10, fig.width=8}
if (!require('riskyr')) install.packages('riskyr'); library('riskyr')

# Use a predefined scenario
my.scenario <- scenarios$n6

summary(my.scenario)


plot(my.scenario, plot.type = "icons")

plot(my.scenario, plot.type = "tree", by = "dc")  # plot tree diagram (splitting N by decision)

plot(my.scenario, plot.type = "curve")  # plot default curve [what = c("prev", "PPV", "NPV")]:

plot(my.scenario, plot.type = "fnet", area = "sq")  # network diagram (with numeric probability labels):

plot(my.scenario, plot.type = "curve", what = "all")  # plot "all" available curves:


```

