## ROC Curves

Code from https://github.com/dariyasydykova/tidyroc README

tidyroc won't be developed further. It seems https://github.com/tidymodels/yardstick does everything tidyroc does and more?

Intro about what ROC curves measure: https://twitter.com/cecilejanssens/status/1104134423673479169?s=03

Why ROC curves are misleading: http://www.fharrell.com/post/mlconfusion/ (Not useful for prediction. PPV/NPV better).


```{r ROC-simple-08-11, message=FALSE, warning=FALSE, eval=FALSE}

if (!require('tidyroc')) remotes::install_github("dariyasydykova/tidyroc"); library('tidyroc')
# remotes::install_github("dariyasydykova/tidyroc")

  library(dplyr)
  library(ggplot2)
  library(broom)
  library(tidyroc)

  glm(am ~ disp,
      family = binomial,
      data = mtcars
  ) %>%
    augment() %>%
    make_roc(predictor = .fitted, known_class = am) %>%
    ggplot(aes(x = fpr, y = tpr)) +
    geom_line() +
    theme_minimal()

```
  
```{r 08-11-ROC-two-models, message=FALSE, warning=FALSE, eval=FALSE}


  # load tidyverse packages
  library(dplyr)
  library(ggplot2)
  library(broom)

  # load cowplot to change plot theme
  library(cowplot)

  # load tidyroc
  library(tidyroc)


  # get `biopsy` dataset from `MASS`
  data(biopsy, package = "MASS")

  # change column names from `V1`, `V2`, etc. to informative variable names
  colnames(biopsy) <-
    c("ID",
      "clump_thickness",
      "uniform_cell_size",
      "uniform_cell_shape",
      "marg_adhesion",
      "epithelial_cell_size",
      "bare_nuclei",
      "bland_chromatin",
      "normal_nucleoli",
      "mitoses",
      "outcome")

  # fit a logistic regression model to predict tumor types
  glm_out1 <- glm(
    formula = outcome ~ clump_thickness + uniform_cell_shape + marg_adhesion + bare_nuclei + bland_chromatin + normal_nucleoli,
    family = binomial,
    data = biopsy
  ) %>%
    augment() %>%
    mutate(model = "m1") # name the model

  # fit a different logistic regression model to predict tumor types
  glm_out2 <- glm(outcome ~ clump_thickness,
                  family = binomial,
                  data = biopsy
  ) %>%
    augment() %>%
    mutate(model = "m2") # name the model

  # combine the two datasets to make an ROC curve for each model
  glm_out <- bind_rows(glm_out1, glm_out2)

  # plot the distribution of fitted values to see both models' outcomes
  glm_out %>%
    ggplot(aes(x = .fitted, fill = outcome)) +
    geom_density(alpha = 0.6, color = NA) +
    scale_fill_manual(values = c("#F08A5D", "#B83B5E")) +
    facet_wrap(~ model)


  # plot ROC curves
  glm_out %>%
    group_by(model) %>% # group to get individual ROC curve for each model
    make_roc(predictor = .fitted, known_class = outcome) %>% # get values to plot an ROC curve
    ggplot(aes(x = fpr, y = tpr, color = model)) +
    geom_line(size = 1.1) +
    geom_abline(slope = 1, intercept = 0, size = 0.4) +
    scale_color_manual(values = c("#48466D", "#3D84A8")) +
    theme_cowplot()


  # plot precision-recall curves using the data-frame we generated in the previous example
  glm_out %>%
    group_by(model) %>% # group to get individual precision-recall curve for each model
    make_pr(predictor = .fitted, known_class = outcome) %>% # get values to plot a precision-recall curve
    ggplot(aes(x = recall, y = precision, color = model)) +
    geom_line(size = 1.1) +
    coord_cartesian(ylim = c(0, 1), xlim = c(0, 1)) +
    scale_color_manual(values = c("#48466D", "#3D84A8")) +
    theme_cowplot()

  glm_out %>%
    group_by(model) %>% # group to get individual AUC values for each ROC curve
    make_roc(predictor = .fitted, known_class = outcome) %>%
    summarise(auc = calc_auc(x = fpr, y = tpr))

  ## # A tibble: 2 x 2
  ##   model   auc
  ##   <chr> <dbl>
  ## 1 m1    0.996
  ## 2 m2    0.910

  glm_out %>%
    group_by(model) %>% # group to get individual AUC values for each precision-recall curve
    make_pr(predictor = .fitted, known_class = outcome) %>%
    summarise(auc = calc_auc(x = recall, y = precision))

  ## # A tibble: 2 x 2
  ##   model   auc
  ##   <chr> <dbl>
  ## 1 m1    0.991
  ## 2 m2    0.951


```
