## Match participants  

***
Usaremos la siguiente [Base de datos](Data/11-Experimental_design/Match_participants.csv)

***
```{r match_participants_libraries, message=FALSE, warning=FALSE}
# Cargamos librerias y leemos DBif (!require('pacman')) install.packages('pacman'); library('pacman')
p_load(optmatch, tidyverse)

# Archivo de data crudos
# RUTs y Edades generadas aleatoriamente
data = read_csv("Data/11-Experimental_design/Match_participants.csv")

head(data)

```


Preparamos la base de datos
```{r match_participants_data_preparation}

# Umbrales para ahorradores y no ahorradores
Criterio_ahorradores = 20
Criterio_no_ahorradores = 2

# Mostramos histograma
hist(data$Porcentaje_ahorro, breaks = 100)
  
# Creamos grupos de Ahorradores (0) y No ahorradores (1)
data$Ahorro = ifelse(data$Porcentaje_ahorro <= Criterio_no_ahorradores, 1,
                      ifelse(data$Porcentaje_ahorro >= Criterio_ahorradores, 0, NA
                      ))

# Cuantos tenemos en cada grupo?
table(data$Ahorro)

#Limpiamos NAs en Ahorro y RUTs duplicados
data = data[complete.cases(data),]
data = data[!duplicated(data$ID),]

#Eliminamos a los Estudiantes
data = data[!grepl("studiante", data$Ocupacion),]

#Recreamos columna ID para los registros que quedan
data$ID = seq(1:nrow(data))
```

Realizamos el matching

**TODO: Como evaluamos si el matching es bueno?**
```{r match_participants}
#Creamos base de parejas
parejas = as.data.frame((pairmatch(Ahorro ~ Edad + Sexo + Educacion, data = data)))
    # caliper establece limites para los matchings
    # print(pairmatch(Ahorro ~ Edad + Sexo + Educacion, caliper = 4.9, data = data), grouped = TRUE)

#Como evaluamos si es buena la seleccion?
# summary(lm(Ahorro ~ Edad + Sexo + Educacion, data = data))

#Añadimos columna ID y renombramos columnas
parejas$ID = seq(1:nrow(data))
colnames(parejas) = c("Group", "ID")

#Combinamos ambas bases y limpiamos
datos_combinados = merge(data, parejas, by = "ID")
datos_combinados = datos_combinados[complete.cases(datos_combinados),]

#Ordenamos por Num de grupo y Ahorro
datos_finales = datos_combinados %>% arrange(Group, Ahorro)

```

```{r match_participants_table}

#Cuantos en cada grupo?
table(datos_finales$Ahorro)

# datos_finales %>% dplyr::select(Edad, Sexo, Educacion, Porcentaje_ahorro)
```
